### ISSUE TITLE
Unbound variable mode

### ISSUE THREAD

**Issue by mjf** [sqids/sqids-bash#8]
Unbound variable causes the script to fail if invoked without arguments:

```shell
$ sqids
sqids: line 1026: mode: unbound variable
```

To fix this add `=` on line [986](https://github.com/sqids/sqids-bash/blob/main/src/sqids#L986):

```bash
    local mode=
```

or perhaps

```bash
    local mode=''
```

so that the variable then will be bound while still empty and the test expresison on the line [1026](https://github.com/sqids/sqids-bash/blob/main/src/sqids#L1026) starts to work as intended. (PS: I won't PR for this.)

**Comment by king-p3nguin** [comment]
Thank you for the bug report! This is fixed now.
